apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: release-workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: This is a system-generated parameter and is required for use in application releases. Refer to https://docs.cloudbees.com/docs/cloudbees-platform/latest/applications/releases#manifest for the expected format
metadata:
  stages/v1alpha1:
    - name: production
      jobs:
        - production
    - name: qa
      jobs:
        - qa
    - name: staging
      jobs:
        - staging
jobs:
  production:
    environment: production
    uses: ./.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ job.environment }}
  qa:
    needs:
      - production
    environment: qa
    uses: ./.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ job.environment }}
  staging:
    needs:
      - qa
    environment: staging
    uses: ./.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ job.environment }}
